### ISSUE TITLE
开发调试环境

### ISSUE THREAD

**Issue by panda1681** [tenlee2012/elasticsearch-analysis-demo#4]
你好，刚刚尝试自己写插件，请问一下怎么搭建开发debug的环境，谢谢！

**Comment by tenlee2012** [comment]
跑test用例，就可以debug了。
https://github.com/tenlee2012/elasticsearch-analysis-demo/blob/master/src/test/java/com/itenlee/search/analysis/DemoTokenizerTest.java
如果你想在ES中调试，那有点麻烦。。
这样是最简单的了。

**Comment by panda1681** [comment]
谢谢
